FROM python:3.10-slim

RUN apt-get update && apt-get install -y git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir flask flask_pymongo werkzeug

# Expose port
EXPOSE 9111

CMD ["python", "app.py"]
