# Base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 8070

# Run the FastAPI app with uvicorn
CMD ["uvicorn", "yolo_api:app", "--host", "0.0.0.0", "--port", "8070"]
